# Apigee pipeline

trigger:
- feature/*
- master
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.23.1'

# Set variables
- bash: |
    echo "##vso[task.setvariable variable=APIGEE_ORG]gcp-solutions-5"
    if [ "$(Build.SourceBranchName)" = "master" ]
    then
      echo "##vso[task.setvariable variable=APIGEE_PROFILE]test"
      echo "##vso[task.setvariable variable=APIGEE_PREFIX]''"
    elif [ "$(Build.SourceBranchName)" = "prod" ]
    then
      echo "##vso[task.setvariable variable=APIGEE_PROFILE]prod"
      echo "##vso[task.setvariable variable=APIGEE_PREFIX]''"
    else
      echo "##vso[task.setvariable variable=APIGEE_PROFILE]test"
      echo "##vso[task.setvariable variable=APIGEE_PREFIX]azureops"
    fi
    mvn clean
  displayName: 'Clean'

- bash: |
    mvn -ntp test -P$(APIGEE_PROFILE) -Dorg=$(APIGEE_ORG) -Ddeployment.suffix=$(APIGEE_PREFIX) -Dusername=$(APIGEE_USERNAME) -Dpassword=$(APIGEE_PASSWORD) -Dcommit=$(Build.SourceVersion) -Dbranch=$(Build.SourceBranchName) -Duser.name=azureops
  displayName: 'Static Code Analysis, Unit Test and Coverage'

- bash: |
    mvn apigee-config:targetservers -P$(APIGEE_PROFILE) -Ddeployment.suffix=$(APIGEE_PREFIX) -Dorg=$(APIGEE_ORG) -Dusername=$(APIGEE_USERNAME) -Dpassword=$(APIGEE_PASSWORD) 
  displayName: 'Pre-deployment configuration'

- bash: |
    mvn -ntp apigee-enterprise:configure -P$(APIGEE_PROFILE) -Ddeployment.suffix=$(APIGEE_PREFIX) -Dorg=$(APIGEE_ORG) -Dusername=$(APIGEE_USERNAME) -Dpassword=$(APIGEE_PASSWORD) 
  displayName: 'Package proxy bundle'

- bash: |
    mvn -ntp apigee-enterprise:deploy -P$(APIGEE_PROFILE) -Ddeployment.suffix=$(APIGEE_PREFIX) -Dorg=$(APIGEE_ORG) -Dusername=$(APIGEE_USERNAME) -Dpassword=$(APIGEE_PASSWORD) 
  displayName: 'Deploy proxy bundle'

- bash: |
    mvn -ntp apigee-config:apiproducts apigee-config:developers apigee-config:apps -P$(APIGEE_PROFILE) -Ddeployment.suffix=$(APIGEE_PREFIX) -Dorg=$(APIGEE_ORG) -Dusername=$(APIGEE_USERNAME) -Dpassword=$(APIGEE_PASSWORD) 
  displayName: 'Post-deployment configuration'

- bash: |
    node ./node_modules/cucumber/bin/cucumber.js target/test/integration/features --format json:target/reports.json
  displayName: 'Functional Test'

